FROM node:20-alpine

WORKDIR /app

# Install build tools needed for native npm modules
RUN apk add --no-cache python3 make g++

EXPOSE 3000

# Install and run dev on startup
CMD ["sh", "-c", "npm install && npm run dev"]
